```{r setup, include=FALSE}
#library(readxl)
#Gamesonyourphone_ <- read_excel("extra/Gamesonyourphone?.xlsx")
#View(Gamesonyourphone_) 
library(viridis)
library(plotly)
library(tidyverse)
library(tidymodels)
library(knitr)
library(xaringanthemer)
library(readxl)
```

```{r import-data}
board_games <- readr::read_csv("/cloud/project/data/board_games.csv")
```

```{r}
board_games%>%
  arrange(desc(max_playtime))

board_games <- board_games %>%
  mutate(
    playtime_group = case_when(
      playing_time < 1 ~ "N/A",
      playing_time >= 1 & playing_time <= 20 ~ "Under 20 minutes",
      playing_time >= 21 & playing_time <= 40 ~ "20-40 minutes",
      playing_time >= 41 & playing_time <= 60 ~ "40-60 minutes",
      playing_time >= 61 & playing_time <= 120 ~ "1-2 hours",
      playing_time >= 121 & playing_time <= 180 ~ "2-3 hours",
      playing_time >= 181 & playing_time <= 240 ~ "3-4 hours",
      playing_time >= 241 & playing_time <= 360 ~ "4-6 hours",
      playing_time >= 361 ~ "Over 6 hours"
    ))
``` 

```{r}
board_games%>%
  count(playtime_group)%>%
  arrange(desc(n))
```


stacked barplot
 

```{r bar-plot, warning = FALSE, echo = FALSE, message = FALSE, fig.alt= "In this graph, we have a histogram displaying the frequency of games in each group of playing times. It reveals that most games are under an hour, with a fairly even split between the groups of 0-20 minutes and 20-40. The 40-60 group has the most number of games. Beyond that, there are a few spikes around convenient time labels such as 2 hours, 3 hours etc, but the vast majority of games lie in this under an hour range."  }
fig1 <-ggplot(data = board_games, aes(playing_time, fill= factor(playtime_group, 
                                                          c("Under 20 minutes",
                                                            "20-40 minutes",
                                                            "40-60 minutes",
                                                            "1-2 hours",
                                                            "2-3 hours",
                                                            "3-4 hours",
                                                            "4-6 hours",
                                                            "over 6 hours",
                                                            "NA")))) +
    geom_histogram() +
    xlim(0,500) +
    labs(title = "Playtime density",
       x = "Playing time (minutes)",
       y = "Count",
       fill = "Length of Play") +
    scale_fill_viridis_d() + 
    theme_minimal()
  
ggplotly(fig1)
```
```{r violin-plot, echo = F, warning = F, message = F, fig.alt = ""}
board_games %>% 
  
ggplot(aes(x = playtime_group , y = average_rating, fill= factor(playtime_group, 
                                                          c("Under 20 minutes",
                                                            "20-40 minutes",
                                                            "40-60 minutes",
                                                            "1-2 hours",
                                                            "2-3 hours",
                                                            "3-4 hours",
                                                            "4-6 hours")))) +
  labs(title = "Rating of games",
       subtitle = "By playtime length",
       fill = "Playtime Group",
       x = "Length of Play",
       y = "Game Rating") +
  theme(axis.text.x=element_text(angle = -45, hjust = 0)) +
  geom_violin()  + 
  scale_x_discrete(limits = c("Under 20 minutes",
                                                            "20-40 minutes",
                                                            "40-60 minutes",
                                                            "1-2 hours",
                                                            "2-3 hours",
                                                            "3-4 hours",
                                                            "4-6 hours"))+ 
  scale_fill_viridis_d()
```

Research questions: Does this change with recommended ages? 
Does this change with different game categories?

```{r best-boardgame, echo = F, warning = F, message = F, fig.alt = ""}
best_boardgame <- board_games %>%
  select(name, average_rating, users_rated)

ggplot(data = best_boardgame, mapping = aes(x = users_rated, y = average_rating,
                                            fill = name)) + 
  geom_point()
```